### ISSUE TITLE
New products not properly rendered in OceanBrowser

### ISSUE THREAD

**Issue by ctroupin** [gher-ulg/EMODnet-Chemistry#4]
## Problem

The new products (v2023) cannot be viewer on OceanBrowser. Example here with chlorophyll-a.
![Screenshot from 2023-08-14 11-55-26](https://github.com/gher-uliege/EMODnet-Chemistry/assets/11868914/09238640-8400-4778-9940-0ce48b4616ae)

## Origin of the problem

Possibly linked to https://github.com/Unidata/netcdf-c/issues/2591.

```bash
root@ddb75bc7a870:/var/www/data/Tests/By_sea_regions/Arctic_Ocean# python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4
>>> ds = netCDF4.Dataset("Water_body_dissolved_oxygen_concentration.4Danl.nc")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'Water_body_dissolved_oxygen_concentration.4Danl.nc'
>>> netCDF4.__version__
'1.3.1'
```

So could be due to "checksum" / flectcher32 in the files.

**Comment by ctroupin** [comment]
## Solution no.1

Use `nco` (recent version) to disable "checksum" / flectcher32 on the files.

On the ogs04 machine this means we have to compile `nco` from source (maybe not so easy, at least when I tried on my machine).

## Solution no.2

Rewrite the files with a previous version of [`NCDatasets`](https://github.com/Alexander-Barth/NCDatasets.jl).

1. Create new environment in Julia:
```julia-repl
(@v1.9) pkg> activate name_of_environment
```
2. Install older version of NCDatasets
```julia
(EMODnet) pkg> add NCDatasets@v0.12.10 
```
2. In the notebook:
```julia
using Pkg
Pkg.activate(path_to_environment)
using NCDatasets
Pkg.status("NCDatasets")
```
4. Open the file in "edit" mode:
```julia-repl
ds = NCDataset(datafile, "a")
close(ds)
```

@Alexander-Barth solution no.2 seems to work, do you think it makes sense to apply on all the files?

**Comment by ctroupin** [comment]
@Alexander-Barth  Finally found:
1. turns out that the previous solution (using an older version of NCDatasets) didn't solve the issue: the file could be read and re-written, but that didn't enable the correct visualisation on OceanBrowser.
2. I noticed that I had reduced the size of the file I tested with `ncks`, and it was in fact this operation that get the file to work in OceanBrowser.

I tested another command, for example `ncatted` (as we need to correct the DOIs), but that didn't solve the issue either.

__Conclusions:__ apply `ncks` like this for example (so the file is not affected)
```bash
ncks -O -d lon,-180.,180. -d lat,-90.,90. Water_body_chlorophyll-a.nc Water_body_chlorophyll-a.nc
```
seems to do the job.

__Question:__ why?

```bash
$ ncatted --version
NCO netCDF Operators version 4.9.9 "Gesundheit!" built by nobody on eeed4cb96914 at May 27 2021 06:43:15
ncatted version 4.9.9
``

**Comment by Alexander-Barth** [comment]
maybe with `ncdump -h -s` we can inspect if some storage attributes changed.

**Comment by ctroupin** [comment]
* `ncdump -h -s` 

| Before    | After  applying `ncks -O`|
| -------- | ------- |
| :_NCProperties = "version=2,netcdf=4.9.2,hdf5=1.14.0"  | :_NCProperties = "version=2,netcdf=4.8.0,hdf5=1.10.6"    |
| :_SuperblockVersion = 2 ; | $:_SuperblockVersion = 2 ;     |
| :_IsNetcdf4 = 1 ;    | :_IsNetcdf4 = 1 ;    |
| :_Format = "netCDF-4" ; | :_Format = "netCDF-4" ; |


* `ncks --hdn -m` 
(print hidden (aka special) attributes; should be the same as `ncdump -s` but seems not exactly the same).

| Before    | After  After  applying `ncks -O`|
| -------- | ------- |
| Water\ body\ phosphate:_Storage = "chunked" ; | Water body phosphate:_Storage = "chunked" ; |
| Water\ body\ phosphate:_ChunkSizes = 1, 1, 100, 100 ; | Water body phosphate:_ChunkSizes = 1, 1, 100, 100 ; |
| Water\ body\ phosphate:_DeflateLevel = 5 ; | Water body phosphate:_Filter = "1,5" ; |
| Water\ body\ phosphate:_Fletcher32 = "true" ; | Water body phosphate:_DeflateLevel = 5 ; |
| Water\ body\ phosphate:_Endianness = "little" ; | Water body phosphate:_Endianness = "little" ; |

**Comment by Alexander-Barth** [comment]
ok, I see the the problematic ckeck summing `_Fletcher32` got removed. Great!

**Comment by ctroupin** [comment]
yes! and there is also a change in the `hdf` version but that's not clear if this relevant.

Anyway let's close the issue with the command I use: not need to perform subsetting as stated before, just this:

```bash
ncks -O filename.nc filename.nc
```
