### ISSUE TITLE
Compressing the product netCDF files?

### ISSUE THREAD

**Issue by ctroupin** [gher-ulg/EMODnet-Chemistry#5]
Shall we apply compression on the netCDF files?

## Example
```bash
ncks -7 -L 1 --baa=4 --ppc default=3 Water_body_chlorophyll-a.4Danl.nc Water_body_chlorophyll-a.4Danl_compressed.nc 
```
Initial size: 4.0G      
Final size: 237M

## Command explanation

* `-7`  (equivalent to --fl_fmt=netcdf4_classic): format to netCDF4 (probably not required in our case)
* `-L 1`: set deflation level to 1 (should be between 1 and 9).
* `--baa=4`: _Bit Adjustment Algorithms_ is set to _Granular BitRound_
* `--ppc`: _Precision Preserving Compression_: preserve three significant digits (value should be adapted)

**Comment by Alexander-Barth** [comment]
The size improvements are quite dramatic. If I understand correctly, this is a lossy compression. What would be the maximum difference between the original data and the compressed one.

**Comment by ctroupin** [comment]
yes with `--baa` and `--ppc` we're doing a lossy compression, which we may prefer to avoid.
Meanwhile I've been testing `ncks -L 1` , `ncks -L 2`, ...

The improvements are not that strong but still make a difference.

Interesting link about _bit grooming_: https://agu.confex.com/agu/fm17/mediafile/Handout/Paper282857/pst_ppc_agu_201712.pdf

**Comment by ctroupin** [comment]
These are the results of the test on a file initially 349M.      
We apply the command 
```bash
ncks -7 -L 1 --baa=4 --ppc default=N in.nc out.nc
```
with N = 1, 2, ... 8

| `--ppc default=n  	| Maximal difference  	| RMS difference   	| File size (in M)| 
|---	|---	|---	|---	|
| 1 | 3.9965029 | 0.05498933 | 90 | 
| 2 | 0.4994774 | 0.0039711986 | 113 | 
| 3 | 0.031248093 | 0.00044728452 | 166 | 
| 4 | 0.0039052963 | 5.6246507e-5 | 205 | 
| 5 | 0.00048828125 | 3.8645726e-6 | 242 | 
| 6 | 3.0517578e-5 | 4.3766843e-7 | 291 | 
| 7 | 0.5 | 0.000117428135 | 316 |

**Comment by Alexander-Barth** [comment]
That's interesting. Maybe discuss this with the emodnet colleagues to check how much precision is needed. Another discussion point would be if we need to keep around the uncompressed files. It is better to have a consensus on these points.

**Comment by ctroupin** [comment]
Sure, I'll bring in the topic during the next meeting.
